apiVersion: apps/v1
kind: Deployment
metadata:
  name: mawrid-vendor
  namespace: prod
  labels:
    app: mawrid-vendor
    type: frontend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      name: mawrid-vendor-pod
      labels:
        app: mawrid-vendor
        type: frontend
    spec:
      containers:
        - name: mawrid-vendor
          image: REPLACE_IMAGE_TAG
