apiVersion: v1
kind: Service
metadata:
  name: mawrid-vendor
  namespace: prod
  labels:
    app: mawrid-vendor
spec:
  type: NodePort
  ports:
    - port: 3005 # External port inside the cluster
      targetPort: 3000 # Port inside the container (your Next.js app)
      nodePort: 30005 # actual public access point (must be in range 30000–32767)
  selector:
    app: mawrid-vendor
    type: frontend
