name: Discord Notifications

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed, reopened, synchronize]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Discord on Push
        if: github.event_name == 'push'
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "username": "GitHub Bot",
            "embeds": [{
              "title": "🚀 New Push to '${{ github.repository }}'",
              "description": "**${{ github.actor }}** pushed to `${{ github.ref }}`\n[View Commit](${{ github.event.head_commit.url }})",
              "color": 3066993
            }]
          }' ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notify Discord on Pull Request
        if: github.event_name == 'pull_request'
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "username": "GitHub Bot",
            "embeds": [{
              "title": "📢 Pull Request: \"${{ github.event.pull_request.title }}\"",
              "description": "**${{ github.actor }}** opened a pull request.\n[View PR](${{ github.event.pull_request.html_url }})",
              "color": 3447003
            }]
          }' ${{ secrets.DISCORD_WEBHOOK_URL }}
